name: Cypress Tests

# Trigger this pipeline automatically every single time code is pushed to the main branch
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase Repository
        uses: actions/checkout@v4

      - name: Run Cypress Automated Suites Cloud-side
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          # This triggers our headless execution script automatically
          command: npm run cy:run